### ISSUE TITLE
make all websites responsive

### ISSUE THREAD

**Issue by adyasha9** [adyasha9/frontend-templates#1]
Please attach a screenshot if you can, to make it easier to view the changes. I will accept PR if I find it suitable.

**Comment by Chauhan-Aniket** [comment]
@adyasha9 can you assign this to me?

**Comment by shivangigoel1302** [comment]
Hey can you assign this to me? Thankyou

**Comment by adyasha9** [comment]
@shivangigoel1302 go ahead

**Comment by ranabirbasu12** [comment]
I'm just getting started with with open source. Can some issue be assigned to two people? Also, what is the procedure after we are given a "go ahead" by the owner. I don't know how pull requests are made.
Also, can this be assigned to me?

**Comment by adyasha9** [comment]
Yes, issues can be assigned to two people , if you received instruction go-ahead that means you can start contributing to the respective project. https://opensource.com/article/19/7/create-pull-request-github go to this link to learn how pull requests are made.

**Comment by adyasha9** [comment]
@ranabirbasu12 Yes, issues can be assigned to two people, if you received instruction go-ahead that means you can start contributing to the respective project. https://opensource.com/article/19/7/create-pull-request-github go to this link to learn how pull requests are made.

**Comment by ranabirbasu12** [comment]
Thank you for the resources, it helped a lot! Can you assign this to me?

**Comment by adyasha9** [comment]
@ranabirbasu12  yes go-ahead

**Comment by rupalkachhwaha** [comment]
Want to contribute to this. Thank you.

**Comment by rupalkachhwaha** [comment]
Please assign this to me.

**Comment by aritrochakraborty29** [comment]
I want to do this..
can you please assign me??

**Comment by adyasha9** [comment]
@rupalkachhwaha go ahead

**Comment by adyasha9** [comment]
@aritrochakraborty29 yes go ahead

**Comment by kartikagarwal9** [comment]
@adyasha9 Hey i wanted to contribute , if you can , please assign the task

**Comment by adyasha9** [comment]
@kartikagarwal9  go ahead and make Task3 responsive.
